### PR TITLE
Sync command indexing with chronological UI view

### LINKED ISSUE #81: Fix index mismatch and implement chronological sorting
- **Problem:** UI chronological sorting caused `edit` and `delete` commands to target incorrect trips because the internal list was unsorted.
- **Fix:** Updated `ModelManager` to use `SortedList` for all list accessors and implemented a default `CHRONOLOGICAL_COMPARATOR` in `Trip.java`.
- **Impact:** Ensures command indices always match the visible UI order.

### PR DESCRIPTION
**Pull request by ths1959**
**Model:** Refactored `ModelManager` to return `sortedTrips` in `getFilteredTripList()`.
**Logic:** Moved sorting criteria to `Trip.java`; added name-based tie-breaking for undated trips.
**UI:** Updated `HelpWindow.java` to include missing `edit`, `find`, and `filter` command syntax.
**Tests:** Updated `FindCommandTest` to account for chronological sorting.

Fixes #81

### CODE REVIEW

File: src/test/java/seedu/triplog/model/trip/TripTest.java [hunk 1]
```diff
@@ -143,4 +143,31 @@ public void constructor_startDateBeforeEndDate_noException() {
         new Trip(name, null, null, null, Collections.emptySet(), startDate, endDate);
         // No exception expected
     }
+
+    @Test
+    public void chronologicalComparator_test() {
```
Comment (derrikzzz) [inline src/test/java/seedu/triplog/model/trip/TripTest.java]: I think we can follow conventions as naming test methods as `featureUnderTest_testScenario_expectedBehavior()` as followed in the codebase!
