### PR TITLE
Throw error when user inputs multiple duplicate tags

### LINKED ISSUE #333: [PE-D][Tester D] Duplicate tags in the add command is silently merged into one
When executing the `add` command, if duplicate tags are included (eg. `t/family t/family`), it shows no warning or error message and simply adds one `family` tag. This can be misleading as the user is expecting there to be two. 

There should be some warning that reminds the user that duplicate tags are not allowed and only one tag will be added to the trip.

Steps to reproduce:
Execute `n/Spain t/family t/family`

Image

-------------
Labels: `severity.Low` `type.FeatureFlaw`

### PR DESCRIPTION
**Pull request by poise3**
Previous commands like "add n/test t/a t/a" was allowed and added a single 'a' tag. Now it throws an error message.

Closes #333 

## Updated
**ParserUtil:** Added a line in `parseTags` method to throw an exception if duplicate tag already exists.

### CODE REVIEW

File: src/main/java/seedu/triplog/logic/parser/ParserUtil.java [hunk 1]
```diff
@@ -119,7 +119,9 @@ public static Set<Tag> parseTags(Collection<String> tags) throws ParseException
         requireNonNull(tags);
         final Set<Tag> tagSet = new HashSet<>();
         for (String tagName : tags) {
-            tagSet.add(parseTag(tagName));
+            if (!tagSet.add(parseTag(tagName))) {
+                throw new ParseException("Duplicate tags are not allowed: " + tagName);
```
Comment (derrikzzz) [inline src/main/java/seedu/triplog/logic/parser/ParserUtil.java]: Perhaps using a named constant in error message here like `MESSAGES_DUPLICATE_TAG` can be better to align with codebase conventions?

**Review by derrikzzz — COMMENTED** [review]
Looks good mostly, just some minor feedback on using named constants for error messages to align with codebase conventions!

**Review by derrikzzz — APPROVED** [review]
Looks good to ship! 🚀
