### PR TITLE
Email validation to reject domains without "."

### LINKED ISSUE #315: [PE-D][Tester D] Emails without a Top-Level Domain (eg. ".com") should not be accepted
Steps to reproduce:
execute `add n/John e/john@gmail`

Image

Expected : Such emails should not be accepted
Actual : Such emails are accepted

-------------
Labels: `severity.Medium` `type.FunctionalityBug`

### PR DESCRIPTION
**Pull request by mingjelly**
This PR aims to resolve issue #315. Previously, email validation accepts emails as long as they had the "@" to separate the domain and the email name. However, a more precise email validation would include a minimal of 1 "." fullstop at the domain field. This helps ensure validity of the email used. Tests for this were also checked and added into the EmailTest to ensure this occurs.

### CODE REVIEW

**Review by derrikzzz — CHANGES_REQUESTED** [review]
Looks good mostly! Just some feedback / clarification on the necessity of changing the regex to match the constraint!

File: src/main/java/seedu/triplog/model/trip/Email.java [hunk 1]
```diff
@@ -34,7 +35,7 @@ public class Email {
             + ALPHANUMERIC_NO_UNDERSCORE + ")*";
 
     // Domain: sequence of labels separated by periods. Suffix length checked in the overall regex.
-    private static final String DOMAIN_REGEX = DOMAIN_LABEL_REGEX + "(\\." + DOMAIN_LABEL_REGEX + ")*";
+    private static final String DOMAIN_REGEX = DOMAIN_LABEL_REGEX + "(\\." + DOMAIN_LABEL_REGEX + ")+";
```
Comment (derrikzzz) [inline src/main/java/seedu/triplog/model/trip/Email.java:38]: Does the regex here need to change to match the constraint on domain name ending with a domain label at least 2 characters long?

Comment (mingjelly) [reply src/main/java/seedu/triplog/model/trip/Email.java:38]: I have amended the domain label requirement back to 1 character! Initially, I took the "." as part of domain label which is why I changed it to at least 2 characters long

**Review by derrikzzz — APPROVED** [review]
The changes look good!
