### PR TITLE
Address issues 357, 327, 323, 306, 283, 281

### LINKED ISSUE #281: [PE-D][Tester E] Inconsistency in functions dealing with filtered views
### Summary
`find` and `filter` commands do not operate on the currently filtered view, unlike `delete`. Filters are not composed, leading to inconsistent behaviour across commands. This could be intended behaviour, but feels slightly unintuitive.

### Steps to Reproduce
1. Apply a filter (e.g., using `filter` or `find`) to display a subset of the trip log.
2. Execute another filtering command such as `find` or `filter`.

### Expected Result
Subsequent `find` or `filter` commands should apply to the currently displayed (filtered) list, composing filters progressively.

### Actual Result
`find` and `filter` operate on the full trip log instead of the currently filtered view, effectively ignoring existing filters.

-------------
Labels: `severity.Medium` `type.FeatureFlaw`

### LINKED ISSUE #283: [PE-D][Tester E] Filter command error message is slightly uninformative
### Summary
Invalid parameters in the `filter` command produce a misleading error message. The parser does not parse arguments other than `sd` and `ed`. In the event the user tries filtering using another prefix, it is parsed as either a start date or end date, leading to the error message that the date formatting is incorrect.

### Steps to Reproduce
1. Execute `filter sd/2026-01-01 ed/2026-03-01 n/hello`.
2. Observe the error message returned.

### Expected Result
The system should indicate that filtering by name (`n/`) is not supported, and clearly specify the valid parameters for the `filter` command.

### Actual Result
The parser treats `2026-03-01 n/hello` as the end date and returns:
`[!!] Dates should be in YYYY-MM-DD format and between 1900-01-01 and 2100-12-31`, implying an incorrect date format even though the date is valid.

-------------
Labels: `severity.Low` `type.FunctionalityBug`

### LINKED ISSUE #306: [PE-D][Tester A] UG & DG: Filter behavior is internally inconsistent
The UG says trips without a start date are ignored by filter, while the DG says the filter logic accepts trips with null sd/ and ed/ fields. This is confusing because a tester cannot tell whether trips with missing dates should be excluded outright, processed but never matched, or treated in some other way.

-------------
Labels: `severity.Low` `type.FunctionalityBug`

### LINKED ISSUE #323: [PE-D][Tester A] DG: Filter sequence diagram note conflicts with the filter paragraph above it.
DG filter documentation is internally inconsistent on how trips with missing dates are handled. In the DG filter section, the paragraph states that the command “accepts trips with null sd/ and ed/ fields.” However, the note inside the sequence diagram says the predicate only filters trips where startDate is not null and within the query range, with endDate checked only if present. This makes it unclear whether trips with missing start dates are accepted, ignored, or rejected during filtering.

-------------
Labels: `severity.Low` `type.FunctionalityBug`

### LINKED ISSUE #327: [PE-D][Tester D] Output message for filter should include the date range
The output message for the `filter` command only shows the success message without including the date range as shown below.

Image

Instead it should include a clearer output like `Found the following trips starting between start_date and end_date`.

-------------
Labels: `severity.Low` `type.FunctionalityBug`

### LINKED ISSUE #357: [PE-D][Tester B] Inconsistency with actual implementation and developer guide
Developer guide says end date is optional

Image

However it is invalid,

Image

-------------
Labels: `severity.High` `type.FunctionalityBug`

### PR DESCRIPTION
**Pull request by 2520th**
- Update find and filter context logic by using two predicates in ModelManager class, each of these two command can override the previous command of the same type, but they can now be applied together.
- Update DG making it less ambiguous.
- Update FilterCommandParser to output the correct invalid format exception.
- Update FilterCommand success message to include date range.

Closes #357 
Closes #327
Closes #323
Closes #306
Closes #283
Closes #281

### CODE REVIEW

File: src/main/java/seedu/triplog/model/ModelManager.java [hunk 1]
```diff
@@ -147,6 +149,25 @@ public void updateFilteredTripList(Predicate<Trip> predicate) {
...
 
+    @Override
+    public void updateFilteredTripList(Predicate<Trip> predicate, boolean isFilter) {
+        requireNonNull(predicate);
+        if (isFilter) {
+            filterPredicate = predicate;
+            if (findPredicate == null) {
+                filteredTrips.setPredicate(filterPredicate);
+                return;
+            }
```
Comment (ths1959) [inline src/main/java/seedu/triplog/model/ModelManager.java:160]: Nice work on the predicate stacking logic! Using two separate fields makes the state management much cleaner and prevents the commands from clobbering each other.

File: src/main/java/seedu/triplog/logic/parser/FilterCommandParser.java [hunk 2]
```diff
@@ -22,13 +27,24 @@ public class FilterCommandParser implements Parser<FilterCommand> {
...
             throw new ParseException(String.format(MESSAGE_INVALID_COMMAND_FORMAT, FilterCommand.MESSAGE_USAGE));
         }
 
+        if (arePrefixesPresent(argMultimap, PREFIX_NAME)
+                || arePrefixesPresent(argMultimap, PREFIX_PHONE)
+                || arePrefixesPresent(argMultimap, PREFIX_EMAIL)
+                || arePrefixesPresent(argMultimap, PREFIX_ADDRESS)
+                || arePrefixesPresent(argMultimap, PREFIX_TAG)) {
+            throw new ParseException(String.format(MESSAGE_INVALID_COMMAND_FORMAT, FilterCommand.MESSAGE_USAGE));
+        }
```
Comment (ths1959) [inline src/main/java/seedu/triplog/logic/parser/FilterCommandParser.java:46]: Good defensive programming here! It ensures users don't get confused by providing extra prefixes that the command doesn't actually process.

File: src/main/java/seedu/triplog/logic/commands/FilterCommand.java [hunk 3]
```diff
@@ -51,9 +51,14 @@ public CommandResult execute(Model model) throws CommandException {
...
-                : trip.getEndDate().value.isBefore(endDate.value.plusDays(1))));
+                : trip.getEndDate().value.isBefore(endDate.value.plusDays(1))),
+                true);
 
-        return new CommandResult(model.getFilteredTripList().isEmpty() ? MESSAGE_NO_TRIPS_FOUND : MESSAGE_SUCCESS);
+        if (model.getFilteredTripList().isEmpty()) {
+            return new CommandResult(MESSAGE_NO_TRIPS_FOUND);
+        } else {
+            return new CommandResult(String.format("%s%s to %s:", MESSAGE_SUCCESS, startDate, endDate));
+        }
```
Comment (ths1959) [inline src/main/java/seedu/triplog/logic/commands/FilterCommand.java:61]: I like the application of the dynamic success message here, it helps with the UX by allowing for users to better catch input mistakes immediately.

**Review by ths1959 — APPROVED** [review]
Solid changes on the code and documentation overall, LGTM!
